apiVersion: v1
kind: Service
metadata:
    name: "tff1test01-ad47"
    labels:
        app: "tff1test01-ad47"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "tff1test01-ad47"