on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n flaskalkCICD -g flaskalkCICDa467-rg --location "France Central" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n flaskalkCICD --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n flaskalkCICD --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n flaskalkCICD --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: flaskalkcicd.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t flaskalkcicd.azurecr.io/tff1test01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push flaskalkcicd.azurecr.io/tff1test01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_tff1test01_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ingress-basic | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ingress-basic`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ingress-basic
        container-registry-url: flaskalkcicd.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: tff1test01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ingress-basic
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          flaskalkcicd.azurecr.io/tff1test01:${{ github.sha }}
        imagepullsecrets: |
          tff1test01dockerauth   
