on: [push, workflow_dispatch]

# Environment variables available to all jobs and steps in this workflow
env:

  CLUSTER_NAME: tff1_test01
  CLUSTER_RESOURCE_GROUP: tff1
  APP_NAME: aks_flaskalk
  NAMESPACE: ingress-basic
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        github-token: f03a8eeb-4f5a-4ab1-af50-f6c3759cc71c
     
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          flaskalk.yaml
        namespace: ${{ env.NAMESPACE }}
